spring:
  application:
    name: projects

  datasource:
    url: jdbc:postgresql://localhost:5432/DB_start
    username: postgres
    password: 153698742
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
